# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_version = ENV["VERSION"]
    increment_version_number(version_number: app_version) if app_version
    
    app_identifier = "com.ttm246.app"
    latest_build_number = latest_testflight_build_number(app_identifier: app_identifier) + 1

    increment_build_number(
      build_number: latest_build_number,
      xcodeproj: "Web-Time-Machine.xcodeproj"
    )
    build_app(
      scheme: "ttm (iOS)",
      output_directory: "./build/",
      export_options: {
        provisioningProfiles: {
          "com.ttm246.app": "match AppStore com.ttm246.app 1708013014",
          "com.ttm246.app.Extension": "match AppStore com.ttm246.app.Extension"
        }
      }
    )
    api_key_json = JSON.parse(ENV["APP_STORE_CONNECT_API_KEY"])
    
    api_key = app_store_connect_api_key(
      key_id: api_key_json["key_id"],
      issuer_id: api_key_json["issuer_id"],
      key_content: api_key_json["key"].gsub('\n', "\n")
    )
  
    upload_to_testflight(
      api_key: api_key,
      app_identifier: "com.ttm246.app"
    )
  end
end
