# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Web-Time-Machine.xcodeproj")
    build_app(scheme: "ttm (iOS)")

    # Define the API Key
    api_key = app_store_connect_api_key(
      key_id: "79RN4BR6S8",
      issuer_id: "738170bc-468e-418e-a7a5-00d7b8a0a2a9",
      key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgE/4vK71EgcxfP2Kc\nGMLBOS3WtCKxqFzkOCMKiZSbGXmgCgYIKoZIzj0DAQehRANCAATUD35B3+jcC1IL\nBcQZJgH+BInvQj/lZZh7BAG39x60n6TI0bptxHE/okmiRR2NizaIpraD5iKpw4qD\nuHeeibf8\n-----END PRIVATE KEY-----"
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "com.ttm246.app"
    )
  end
end
