name: Deploy to TestFlight

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Deploy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build and Upload to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          echo "$APP_STORE_CONNECT_API_KEY" > api_key.json
          fastlane beta

      - name: Upload IPA to GitHub Releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TTM_GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./WebTimeMachine.ipa
          asset_name: WebTimeMachine.ipa
          asset_content_type: application/octet-stream
