name: iOS Build and Deploy Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    name: Build and Deploy iOS Safari Extension
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Ruby Dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: ./xcode-client

      - name: Setup .env file
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > ./.env
          echo "REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}" >> ./.env
          echo "REACT_APP_SUPABASE_ANON_KEY=${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}" >> ./.env
        working-directory: ./react-app
      
      - name: Install Node.js Dependencies and Build React Native App
        run: |
          npm install
          npm run build
        working-directory: ./react-app

      - name: Decode and Install Apple Provisioning Profiles and Certificate
        run: |
            echo "${{ secrets.ENCODED_CERTIFICATE }}" | base64 --decode --output cert.p12
            echo "${{ secrets.ENCODED_PROVISIONING_PROFILE_APP }}" | base64 --decode --output app.mobileprovision
        
            KEYCHAIN_PATH=$RUNNER_TEMP/my_temporary.keychain
            security create-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" $KEYCHAIN_PATH
            security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
            security unlock-keychain -p "${{ secrets.KEYCHAIN_PASSWORD }}" $KEYCHAIN_PATH
            security import cert.p12 -P "${{ secrets.P12_PASSWORD }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
            security list-keychains -d user -s $KEYCHAIN_PATH
            security default-keychain -s $KEYCHAIN_PATH
            security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "${{ secrets.KEYCHAIN_PASSWORD }}" $KEYCHAIN_PATH
        
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp app.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
        env:
          ENCODED_CERTIFICATE: ${{ secrets.ENCODED_CERTIFICATE }}
          ENCODED_PROVISIONING_PROFILE_APP: ${{ secrets.ENCODED_PROVISIONING_PROFILE_APP }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

      - name: Execute Fastlane Match
        run: |
            fastlane match appstore --readonly --app_identifier "com.ttm246.app" --git_url "https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/webtimemachine/wtm-cert.git"
        env:
            MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        working-directory: ./xcode-client

      - name: Build and Upload to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          echo "$APP_STORE_CONNECT_API_KEY" > api_key.json
          fastlane beta
        working-directory: ./xcode-client

      - name: Get Release Upload URL
        id: get_release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const core = require('@actions/core');
            const github = require('@actions/github');
            const context = github.context;
      
            // Extract the tag from context.ref by removing the 'refs/tags/' prefix
            const tag = context.ref.replace('refs/tags/', '');
            console.log(`Searching for the release associated with tag: ${tag}`);
      
            try {
              const release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: tag
              });
      
              // If the upload URL is found, set it as an output
              if (release.data.upload_url) {
                console.log(`Upload URL found: ${release.data.upload_url}`);
                core.setOutput('upload_url', release.data.upload_url);
              } else {
                core.setFailed('Upload URL not found for the release.');
              }
            } catch (error) {
              // Handle errors in getting the release by tag, such as if the release does not exist
              core.setFailed(`Error fetching the release by tag: ${error.message}`);
            }
      

      - name: Upload IPA to GitHub Releases
        uses: actions/upload-release-asset@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./xcode-client/build/WebTimeMachine.ipa
          asset_name: WebTimeMachine.ipa
          asset_content_type: application/octet-stream

        
